workflows:
  android-app:
    name: Build Android App
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - laskoforex1@gmail.com
